apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: 733101439357.dkr.ecr.ap-south-1.amazonaws.com/simplebank:aea077595509a2da0d2f5d1f71eb118fd9f0183e
        ports:
        - containerPort: 8080